namespace SharpWinNTInterop.RegistryAPI;

using static ACCESS_MASK;

public static partial class DesiredKeyAccess
{
    public const int
    KEY_QUERY_VALUE = 0x0001,
    KEY_SET_VALUE = 0x0002,
    KEY_CREATE_SUB_KEY = 0x0004,
    KEY_ENUMERATE_SUB_KEYS = 0x0008,
    KEY_NOTIFY = 0x0010,
    KEY_CREATE_LINK = 0x0020;

    public const ulong
    KEY_READ = (STANDARD_RIGHTS_READ | KEY_QUERY_VALUE | KEY_ENUMERATE_SUB_KEYS | KEY_NOTIFY) & ~SYNCHRONIZE,
    KEY_WRITE = (STANDARD_RIGHTS_WRITE | KEY_SET_VALUE | KEY_CREATE_SUB_KEY) & ~SYNCHRONIZE,
    KEY_EXECUTE = KEY_READ & ~SYNCHRONIZE,
    KEY_ALL_ACCESS = (STANDARD_RIGHTS_ALL | KEY_QUERY_VALUE | KEY_SET_VALUE | KEY_CREATE_SUB_KEY | KEY_ENUMERATE_SUB_KEYS | KEY_NOTIFY | KEY_CREATE_LINK) & ~SYNCHRONIZE;
}
